"""Curated activities are content, never fabricated user data."""


def activity(key, title, kind, category, minutes, benefit, steps, tags):
    return dict(
        id=key,
        title=title,
        type=kind,
        category=category,
        minutes=minutes,
        benefit=benefit,
        steps=steps,
        tags=tags,
        level="All levels",
    )


CATALOG = [
    activity(
        "breathing-3",
        "A little room to breathe",
        "breathing",
        "Mind",
        3,
        "A gentle pause when the workday feels full.",
        [
            "Sit comfortably and let your shoulders drop.",
            "Breathe in gently for four counts. Breathe out for six.",
            "Use your natural rhythm if counting feels uncomfortable. Stop if you feel dizzy.",
            "Notice one thing you can leave for later.",
        ],
        ["calm", "stress", "meetings"],
    ),
    activity(
        "grounding-2",
        "Come back to this moment",
        "grounding",
        "Mind",
        2,
        "Turn your attention toward your surroundings.",
        [
            "Feel your feet against the floor.",
            "Name five things you see, four you feel, and three you hear.",
            "Notice two scents and one taste, or simply notice your next breath.",
        ],
        ["overwhelmed", "calm"],
    ),
    activity(
        "meditation-5",
        "The quiet between tasks",
        "meditation",
        "Mind",
        5,
        "Make space for a calmer next step.",
        [
            "Find a comfortable seat. Keep your eyes open or softly closed.",
            "Notice your natural breath without changing it.",
            "When a thought appears, acknowledge it and return to breathing.",
            "Feel your feet, look around, and ease back into your day.",
        ],
        ["calm", "stress"],
    ),
    activity(
        "meditation-10",
        "One thing at a time",
        "meditation",
        "Focus",
        10,
        "Practice bringing your attention back gently.",
        [
            "Settle into your seat and put distractions aside.",
            "Choose your breath as an anchor.",
            "Count each exhale up to ten, then begin again.",
            "Losing count is fine. Begin again without judgment.",
            "Choose one manageable task to return to.",
        ],
        ["focus", "motivation"],
    ),
    activity(
        "meditation-15",
        "Leave the workday behind",
        "meditation",
        "Recovery",
        15,
        "Create a boundary between work and personal time.",
        [
            "Find a quiet spot away from your workspace.",
            "Notice your face, shoulders, hands, and feet in turn.",
            "Allow each area to soften without forcing it.",
            "Acknowledge unfinished tasks; they can wait for your next workday.",
            "Think of one small thing you want to enjoy this evening.",
        ],
        ["sleep", "relaxation", "boundaries"],
    ),
    activity(
        "meditation-20",
        "A softer landing",
        "meditation",
        "Recovery",
        20,
        "An unhurried body scan for winding down.",
        [
            "Sit or lie somewhere comfortable. Adjust whenever you need.",
            "Bring attention slowly from your toes through your legs.",
            "Notice your back, shoulders, arms, and hands.",
            "Let your jaw soften and your breath find its own pace.",
            "Rest with the sensations of your whole body. Return slowly when ready.",
        ],
        ["sleep", "relaxation"],
    ),
    activity(
        "stretch-3",
        "Unfold your afternoon",
        "movement",
        "Body",
        3,
        "A comfortable movement break from sitting.",
        [
            "Stand if comfortable, or stay seated.",
            "Gently roll your shoulders and open your hands.",
            "Reach within a comfortable range. Avoid painful movements.",
            "Look away from the screen before returning.",
        ],
        ["energy", "meetings"],
    ),
    activity(
        "walk-5",
        "A change of scenery",
        "walk",
        "Environment",
        5,
        "A short walk at your own pace.",
        [
            "Choose a safe, accessible route indoors or outside.",
            "Put your screen away while walking.",
            "Notice light, shapes, or sounds along the way.",
            "Return when you feel ready.",
        ],
        ["energy", "break"],
    ),
    activity(
        "music-5",
        "Let the day settle",
        "music",
        "Mind",
        5,
        "Listen to a track you enjoy with full attention.",
        [
            "Choose a favorite song, or use the optional ambient sound.",
            "Set a comfortable volume.",
            "Notice the rhythm and the space between sounds.",
            "Let the final notes fade before returning.",
        ],
        ["calm", "motivation"],
    ),
    activity(
        "focus-5",
        "Find your next small win",
        "focus",
        "Focus",
        5,
        "Make the next task feel approachable.",
        [
            "Write down what is competing for your attention.",
            "Choose one task that can begin in two minutes.",
            "Close one unnecessary tab or distraction.",
            "Take the first small step. Progress can be modest.",
        ],
        ["focus", "motivation", "deadlines"],
    ),
    activity(
        "connection-3",
        "A moment of connection",
        "social",
        "Social",
        3,
        "Make room for support from someone you trust.",
        [
            "Think of someone you feel comfortable contacting.",
            "Draft a simple message: Do you have time for a quick catch-up?",
            "Choose whether to send it yourself. MoodMentor will not send it.",
            "If now is not a good time, plan a later conversation.",
        ],
        ["connection", "lonely"],
    ),
    activity(
        "gratitude-2",
        "Notice something good",
        "journaling",
        "Mind",
        2,
        "Give a small positive moment your attention.",
        [
            "Think of one ordinary thing you appreciated today.",
            "Name what made it meaningful.",
            "Hold that moment in mind; you do not have to feel grateful for everything.",
        ],
        ["gratitude", "motivation"],
    ),
    activity(
        "break-2",
        "Permission to pause",
        "break",
        "Recovery",
        2,
        "Step away from constant input.",
        [
            "Look away from your screen.",
            "Take a sip of water if you want.",
            "Relax your hands and shoulders.",
            "Decide whether you need more rest before returning.",
        ],
        ["break", "meetings", "energy"],
    ),
    activity(
        "game-2",
        "Find five little details",
        "game",
        "Mind",
        2,
        "A playful attention reset with your surroundings.",
        [
            "Find something round, something green, and something soft.",
            "Find a repeating pattern nearby.",
            "Notice one small detail you had not seen before.",
        ],
        ["focus", "break"],
    ),
]
BY_ID = {a["id"]: a for a in CATALOG}
